# Generated by Django 5.0.6 on 2024-06-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
    ]
